"""empty message

Revision ID: 0d29f2d2a67c
Revises: 6f4ed5c9157c
Create Date: 2019-11-01 23:18:59.445895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d29f2d2a67c'
down_revision = '6f4ed5c9157c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certs', sa.Column('payer_id', sa.Integer(), nullable=True))
    op.drop_constraint('certs_ibfk_1', 'certs', type_='foreignkey')
    op.create_foreign_key(None, 'certs', 'user', ['payer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('certs', 'consumer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certs', sa.Column('consumer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'certs', type_='foreignkey')
    op.create_foreign_key('certs_ibfk_1', 'certs', 'user', ['consumer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('certs', 'payer_id')
    # ### end Alembic commands ###
