"""empty message

Revision ID: 59e223f571dc
Revises: a0681efc5407
Create Date: 2019-11-06 11:03:30.581183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e223f571dc'
down_revision = 'a0681efc5407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('filename', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'filename')
    # ### end Alembic commands ###
