"""empty message

Revision ID: 7b2d8d464098
Revises: 8011fb89649d
Create Date: 2019-11-07 07:12:02.115603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2d8d464098'
down_revision = '8011fb89649d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=40), nullable=True))
    op.add_column('user', sa.Column('pub_key', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pub_key')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
