"""empty message

Revision ID: 8011fb89649d
Revises: 59e223f571dc
Create Date: 2019-11-06 22:40:29.025421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8011fb89649d'
down_revision = '59e223f571dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('updatetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'updatetime')
    # ### end Alembic commands ###
