"""empty message

Revision ID: 8f446dbe2169
Revises: 718326402a65
Create Date: 2019-11-01 22:09:14.156596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f446dbe2169'
down_revision = '718326402a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resource_ibfk_1', 'resource', type_='foreignkey')
    op.create_foreign_key(None, 'resource', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.create_foreign_key('resource_ibfk_1', 'resource', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
