"""empty message

Revision ID: 9894cd6e3b4a
Revises: e43f694e75b3
Create Date: 2019-11-02 18:39:30.149512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9894cd6e3b4a'
down_revision = 'e43f694e75b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('certs', sa.Column('value', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_certs_timestamp'), 'certs', ['timestamp'], unique=False)
    op.add_column('resource', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('resource', sa.Column('title', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'title')
    op.drop_column('resource', 'price')
    op.drop_index(op.f('ix_certs_timestamp'), table_name='certs')
    op.drop_column('certs', 'value')
    op.drop_column('certs', 'timestamp')
    # ### end Alembic commands ###
