"""empty message

Revision ID: a0681efc5407
Revises: 11fb5066f494
Create Date: 2019-11-04 11:33:23.383262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0681efc5407'
down_revision = '11fb5066f494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certs', sa.Column('timestamp_pay', sa.DateTime(), nullable=True))
    op.add_column('certs', sa.Column('timestamp_trans', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_certs_timestamp_pay'), 'certs', ['timestamp_pay'], unique=False)
    op.drop_index('ix_certs_timestamp', table_name='certs')
    op.drop_column('certs', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certs', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.create_index('ix_certs_timestamp', 'certs', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_certs_timestamp_pay'), table_name='certs')
    op.drop_column('certs', 'timestamp_trans')
    op.drop_column('certs', 'timestamp_pay')
    # ### end Alembic commands ###
