"""empty message

Revision ID: e43f694e75b3
Revises: ff181c35c625
Create Date: 2019-11-02 00:47:59.240299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43f694e75b3'
down_revision = 'ff181c35c625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('certs_ibfk_3', 'certs', type_='foreignkey')
    op.create_foreign_key(None, 'certs', 'user', ['transfer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'certs', type_='foreignkey')
    op.create_foreign_key('certs_ibfk_3', 'certs', 'user', ['transfer_id'], ['id'])
    # ### end Alembic commands ###
